#!/bin/bash

SCRIPTSDIR=/home/iggut/.config/hypr/scripts

# Kill already running process
_ps=(sfwbar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
#${SCRIPTSDIR}/statusbar &
sfwbar -m DP-1 & 
sfwbar -m HDMI-A-1 & 


#insync start &
#dropbox &
#telegram-desktop &
#discord &
#nm-applet-indicator
#variety &
